### ISSUE TITLE
Can i install it on windows 

### ISSUE THREAD

**Issue by nedyalkodimitrov** [nano-interactive/cassandra-php-driver#62]
Can i install this driver on windows and use it with laravel 9. This is crucial for our bussines.

**Comment by danielhe4rt** [comment]
Hey!

I'm not so sure if we have some tutorial ready for WIndows users but yes, you probably can install the driver on Windows.

And about the Laravel: We're also working on a integration of Laravel 9/10 to fully integrate ScyllaDB.

Still in development but you check it out here: [Scylloquent](https://github.com/DanielHe4rt/scylloquent)

**Comment by CodeLieutenant** [comment]
You can try to build the latest tag for Windows, but we don't guarantee that it will build. The driver works for Linux, that's the only thing we test currently. In the latest branch of 1.3.x I removed Windows support, cause it's real pain to get it working properly (build PHP in Debug mode for Windows, build libs, and other stuff).

If you are developing on Windows, please use WSL.

We need someone who knows PHP Extension development and Windows Native development in order to support Windows.

**Comment by nedyalkodimitrov** [comment]
Thank you very much for your reply. I will follow with interest what happens with Scylloquent!
