### ISSUE TITLE
[ERROR] Could not retrieve sharding info from connection

### ISSUE THREAD

**Issue by evll** [nano-interactive/cassandra-php-driver#73]
When using this extension for Cassandra >= 4, the following error occurs on connection:
`cassandra | [ERROR] Could not retrieve sharding info from connection to xx.xxx.75. Continuing WITHOUT SHARD-AWARENESS. (connector.cpp:315)`

The error does not prevent the connection from working, but it's polluting logs and is annoying in general.

Cassandra does not support shard-awareness, so is there a way to disable this functionality for it?

**Comment by CodeLieutenant** [comment]
This is scylla aware driver first. I can add cassandra-cpp as build param if it's important to you

**Comment by CodeLieutenant** [comment]
Driver is not tested on Cassandra 4.x, only on 3.x as this is what scylladb is based on

**Comment by evll** [comment]
> This is scylla aware driver first. I can add cassandra-cpp as build param if it's important to you

I would really appreciate that, thanks!

**Comment by CodeLieutenant** [comment]
I'll create seperate branch for that so that you can test it if it works

**Comment by CodeLieutenant** [comment]
Sorry for the wait, I was on vaccation for a long time (a little bit burnt out).
I have implemented dynamic loading of `libcassandra` instead of `libscylladb` on #81 this pull request.
If you still need this feature, testing it would be helpful.


Now this library will officially support `libcassandra` behind a CMake option `-DPHP_SCYLLADB_USE_LIBCASSANDRA=ON`.
By default now everything is dynamically linked instead of static and compiling, so the building process is a little bit changed for dynamic linking as it requires `LibUV` and `LibScyllaDB/LibCassandra` to be present on the running system. There is also a way to compile from source with CMake option if you prefer it that way:

For LibUV compilation: `-DPHP_SCYLLADB_LIBUV_FROM_SRC=ON -DPHP_SCYLLADB_LIBUV_STATIC=ON`
For LibScyllaDB: `-DPHP_SCYLLADB_LIBSCYLLADB_FROM_SRC=ON -DPHP_SCYLLADB_LIBSCYLLADB_STATIC=ON`
For CassandraDB `-DPHP_SCYLLADB_LIBCASSANDRA_FROM_SRC=ON -PHP_SCYLLADB_LIBCASSANDRA_STATIC=ON`


If you need any help please reopen this Issue

**Comment by evll** [comment]
FYI: we tested the `ReleaseLibCassandra` preset, and it worked well, thank you!
